version: '3.7'

services:

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 5173:80
    environment:
      - CHOKIDAR_USEPOLLING=true